### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team2#75]
_From @yossigil on November 14, 2018 20:39_

Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

_Copied from original issue: TechnionYP5779/team6#90_

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#133

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#119

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#93

**Comment by nerya50** [comment]
done in commit f11cff1af6f98aa7e0afd40a6ab52a29b9e24e0d

**Comment by yossigil** [comment]
`    @NotNull public Asserter andAye(final @NotNull String reason, final boolean claim) {
      azzert.that(reason, claim, is(true));
      return this;
    }`

oops, you forgot those. please check that there are no others like this

**Comment by nerya50** [comment]
@yossigil can't find how to use assert with reason, so i have used assertTrue and assertFalse. is it good enough?
`
@NotNull public Asserter andAye(final @NotNull String reason, final boolean claim) {
      azzert.assertTrue(reason, claim);
      return this;
    }

@NotNull public Asserter andNay(final @NotNull String reason, final boolean claim) {
      azzert.assertFalse(reason, claim);
      return this;
    }
`

**Comment by yossigil** [comment]
can this be closed?

**Comment by nerya50** [comment]
If assertTrue and assertFalse are good enough, so it can be closed.
My question is if yore requirements are answered by the current state
